version: "3"
services:
        reverse-proxy:
                image: traefik
                restart: always
                ports:
                        - 80:80
                        - 8080:8080
                        - 443:443
                networks:
                        - proxy
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ${PWD}/config/traefik.toml:/traefik.toml
                        - ${PWD}/config/acme.json:/acme.json
                container_name: traefik
networks:
        proxy:
                external: true
