logLevel = "WARN" # options: DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["https","http"]

[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mywebsite.com" # [CHANGEME]
watch = true
exposedByDefault = false

[acme]
email = "certificates@mywebsite.com" # [CHANGEME]
storage = "/acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
